### ISSUE TITLE
"Permission Denied" error when withdrawing from LNbank wallet.

### ISSUE THREAD

**Issue by naturallaw777** [dennisreimann/btcpayserver-plugin-lnbank#39]
I am running BTCPay server via https://github.com/fort-nix/nix-bitcoin/ via Caddy webserver.

I am running my own LND node with good balanced liquidity and channel connections. 

BTCPay server is connected to my LND node. 

All my BTCPay server stores and POSs work perfect with my LND node. 

I am running BTCPay Server v1.10.2, Caddy 2.6.4, Bticoin core 24.1, LND node 0.16.2-beta, LNBank 1.6.2, NixOS 23.05 (For Nix-Bitcion), NixOS 23.11 systemwide. 

This issue is when I create a new bank with LNBank plug in, I am able to send sats into the wallet; HOWEVER, when I go to withdraw or pay an invoice with the new LNbank wallet, I get an error "Permission Denied." Thus, I am unable to retrieve my funds.

I have tried most things to trouble shoot, like creating a new bank, creating a brand new store, creating a brand new BTCPayserver instance with a new database and still the same error. 

I am the only account on BTCPay server as admin. 

Below are some file snipits:

Caddy (NixOS):
```
"${personalization.btcpayserver_url}" = {
	extraConfig = ''
	reverse_proxy :23000
	encode gzip zstd
	'';
};
```
BTCPay server (NixOS):

```
  services.btcpayserver = {
    enable = true;
  };

```
Error for BTCPay Server:
```
Jul 26 08:57:53 nixos btcpayserver[4165]: BTCPayServer.Lightning.LND.LndException: payment isn't initiated
Jul 26 08:57:53 nixos btcpayserver[4165]:    at BTCPayServer.Lightning.LND.LndClient.LndPaymentClientSession.ListenLoop(HttpRequestMessage request)
Jul 26 08:57:53 nixos btcpayserver[4165]:    at BTCPayServer.Lightning.LND.LndClient.LndPaymentClientSession.WaitPayment(CancellationToken cancellation)
Jul 26 08:57:53 nixos btcpayserver[4165]:    at BTCPayServer.Lightning.LND.LndClient.GetPayment(String paymentHash, CancellationToken cancellation)
Jul 26 08:57:53 nixos btcpayserver[4165]:    at BTCPayServer.Lightning.LND.LndClient.BTCPayServer.Lightning.ILightningClient.GetPayment(String paymentHash, CancellationToken cancellation)
Jul 26 08:57:53 nixos btcpayserver[4165]:    at BTCPayServer.Controllers.Greenfield.GreenfieldLightningNodeApiController.GetPayment(String cryptoCode, String paymentHash, CancellationToken cancellationToken) in /build/source/BTCPayServer/Controllers/GreenField/GreenfieldLightningNodeApiController.cs:line 205
Jul 26 08:57:53 nixos btcpayserver[4165]:    at BTCPayServer.Controllers.Greenfield.LocalBTCPayServerClient.GetLightningPayment(String cryptoCode, String paymentHash, CancellationToken token) in /build/source/BTCPayServer/Controllers/GreenField/LocalBTCPayServerClient.cs:line 1101
Jul 26 08:57:53 nixos btcpayserver[4165]:    at BTCPayServer.Plugins.LNbank.Services.BTCPayService.GetLightningPayment(String paymentHash, CancellationToken cancellationToken) in /build/BTCPayServer.Plugins.LNbank/Services/BTCPayService.cs:line 44
Jul 26 08:57:53 nixos btcpayserver[4165]:    at BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher.CheckPayment(WalletService walletService, Transaction transaction, CancellationToken cancellationToken) in /build/BTCPayServer.Plugins.LNbank/Services/LightningInvoiceWatcher.cs:line 215
Jul 26 08:57:58 nixos btcpayserver[4165]: fail: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Unable to resolve payment (Payment Hash = 19cb7c8ed348bad4724aa3fedb2f96c451715f24315ac9bf991056ee88e4c02e) for transaction 59ea4ab7-d3e1-4349-9dfb-824320e53c1b
```
LND Error:

```
Jul 26 08:55:43 nixos lnd[3724]: 2023-07-26 08:55:43.767 [ERR] RPCS: [/routerrpc.Router/TrackPaymentV2]: rpc error: code = NotFound desc = payment isn't initiated
Jul 26 08:55:44 nixos lnd[3724]: 2023-07-26 08:55:44.995 [INF] CRTR: Processed channels=0 updates=76 nodes=0 in last 1m0.000306928s
Jul 26 08:55:48 nixos lnd[3724]: 2023-07-26 08:55:48.775 [ERR] RPCS: [/routerrpc.Router/TrackPaymentV2]: rpc error: code = NotFound desc = payment isn't initiated
Jul 26 08:55:53 nixos lnd[3724]: 2023-07-26 08:55:53.782 [ERR] RPCS: [/routerrpc.Router/TrackPaymentV2]: rpc error: code = NotFound desc = payment isn't initiated
Jul 26 08:55:58 nixos lnd[3724]: 2023-07-26 08:55:58.442 [ERR] RPCS: [/lnrpc.Lightning/SendPaymentSync]: permission denied
```

Thanks for any help!

**Comment by naturallaw777** [comment]
Solved with a work around:

in the nix-bitcoin module you need to set LND as this

```

  services.lnd = {
    enable = true;
    restAddress = "127.0.0.1";
    rpcAddress = "127.0.0.1";
    macaroons.btcpayserver.permissions = lib.mkForce ''
      {"entity":"address","action":"write"},
      {"entity":"info","action":"read"},
      {"entity":"info","action":"write"},
      {"entity":"invoices","action":"read"},
      {"entity":"invoices","action":"write"},
      {"entity":"macaroon","action":"generate"},
      {"entity":"macaroon","action":"read"},
      {"entity":"macaroon","action":"write"},
      {"entity":"message","action":"read"},
      {"entity":"message","action":"write"},
      {"entity":"offchain","action":"read"},
      {"entity":"offchain","action":"write"},
      {"entity":"onchain","action":"read"},
      {"entity":"onchain","action":"write"},
      {"entity":"peers","action":"read"},
      {"entity":"peers","action":"write"},
      {"entity":"signer","action":"generate"},
      {"entity":"signer","action":"read"}
    '';

```

Then it will work

**Comment by naturallaw777** [comment]
Will close this issue.

**Comment by naturallaw777** [comment]
Will close this issue

**Comment by erikarvstedt** [comment]
https://github.com/dennisreimann/btcpayserver-plugin-lnbank/issues/39#issuecomment-1654540778 shows the complete set of available permissions (`admin.macaroon`). I suggested to use these for debugging.
In a real world deployment, you should remove all unneeded permissions.
