### ISSUE TITLE
Duplicated Payment Entries (object failed)

### ISSUE THREAD

**Issue by damanic** [dennisreimann/btcpayserver-plugin-lnbank#46]
User sends multiple successful payments to Kraken using the LNBANK UI.  On paying for a fourth invoice the LNBank UI fails with error "object failed".

The user repeats the payment attempt and ends up with three transactions in LNBank that have deducted his balance, all for the same invoice.  Kraken received a single payment, and the LND node confirms only a single payment sent.

Screenshot: 
![image](https://github.com/dennisreimann/btcpayserver-plugin-lnbank/assets/5227303/172bdc18-c80a-4ca3-92ae-34989dc61a1b)

This outcome is alarming to the user, as they believe they have lost funds.    

Should there be some sort of protection or automatic correction when LNBank has a transaction entry that does not correlate with activity on the LN Node?

**Comment by dennisreimann** [comment]
Thanks for reporting. Can you provide teh server logs for that period? `docker logs -f generated_btcpayserver_1`

**Comment by damanic** [comment]
This appears to be the relevant section:

```
2023-11-06T07:42:01.029813544Z info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Transaction 731827d3-d07c-40f3-9095-d3d839ee19f7 status: Pending
2023-11-06T07:42:01.503344310Z fail: BTCPayServer.Plugins.LNbank.Pages.Wallets.SendModel: Payment failed: Object reference not set to an instance of an object.
2023-11-06T07:42:01.503391306Z System.NullReferenceException: Object reference not set to an instance of an object.
2023-11-06T07:42:01.503771125Z    at BTCPayServer.Plugins.LNbank.Services.Wallets.WalletService.SendExternal(Transaction sendingTransaction, LightMoney amount, LightMoney walletBalance, Single maxFeePercent, CancellationToken cancellationToken) in /build/BTCPayServer.Plugins.LNbank/Services/Wallets/WalletService.cs:line 243
2023-11-06T07:42:01.503946644Z    at BTCPayServer.Plugins.LNbank.Services.Wallets.WalletService.SendExternal(Transaction sendingTransaction, LightMoney amount, LightMoney walletBalance, Single maxFeePercent, CancellationToken cancellationToken) in /build/BTCPayServer.Plugins.LNbank/Services/Wallets/WalletService.cs:line 275
2023-11-06T07:42:01.504148527Z    at BTCPayServer.Plugins.LNbank.Services.Wallets.WalletService.Send(Wallet wallet, BOLT11PaymentRequest bolt11, String description, LightMoney explicitAmount, String withdrawConfigId, Single maxFeePercent, CancellationToken cancellationToken) in /build/BTCPayServer.Plugins.LNbank/Services/Wallets/WalletService.cs:line 140
2023-11-06T07:42:01.504259028Z    at BTCPayServer.Plugins.LNbank.Pages.Wallets.SendModel.OnPostConfirmAsync(String walletId) in /build/BTCPayServer.Plugins.LNbank/Pages/Wallets/Send.cshtml.cs:line 171
2023-11-06T07:42:06.048728560Z info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Transaction 731827d3-d07c-40f3-9095-d3d839ee19f7 status: Pending
2023-11-06T07:42:09.433562861Z fail: BTCPayServer.Plugins.LNbank.Pages.Wallets.SendModel: Payment failed: Object reference not set to an instance of an object.
2023-11-06T07:42:09.433617517Z System.NullReferenceException: Object reference not set to an instance of an object.
2023-11-06T07:42:09.433623518Z    at BTCPayServer.Plugins.LNbank.Services.Wallets.WalletService.SendExternal(Transaction sendingTransaction, LightMoney amount, LightMoney walletBalance, Single maxFeePercent, CancellationToken cancellationToken) in /build/BTCPayServer.Plugins.LNbank/Services/Wallets/WalletService.cs:line 243
2023-11-06T07:42:09.433629379Z    at BTCPayServer.Plugins.LNbank.Services.Wallets.WalletService.SendExternal(Transaction sendingTransaction, LightMoney amount, LightMoney walletBalance, Single maxFeePercent, CancellationToken cancellationToken) in /build/BTCPayServer.Plugins.LNbank/Services/Wallets/WalletService.cs:line 275
2023-11-06T07:42:09.433634468Z    at BTCPayServer.Plugins.LNbank.Services.Wallets.WalletService.Send(Wallet wallet, BOLT11PaymentRequest bolt11, String description, LightMoney explicitAmount, String withdrawConfigId, Single maxFeePercent, CancellationToken cancellationToken) in /build/BTCPayServer.Plugins.LNbank/Services/Wallets/WalletService.cs:line 140
2023-11-06T07:42:09.433639874Z    at BTCPayServer.Plugins.LNbank.Pages.Wallets.SendModel.OnPostConfirmAsync(String walletId) in /build/BTCPayServer.Plugins.LNbank/Pages/Wallets/Send.cshtml.cs:line 171
2023-11-06T07:42:11.072479590Z info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Transaction 72527b66-6816-481b-918a-9893dcbf66f0 status: Pending
2023-11-06T07:42:11.072540076Z info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Transaction 731827d3-d07c-40f3-9095-d3d839ee19f7 status: Pending
2023-11-06T07:42:12.992671594Z fail: BTCPayServer.Plugins.LNbank.Pages.Wallets.SendModel: Payment failed: Object reference not set to an instance of an object.
2023-11-06T07:42:12.992705292Z System.NullReferenceException: Object reference not set to an instance of an object.
2023-11-06T07:42:12.992709304Z    at BTCPayServer.Plugins.LNbank.Services.Wallets.WalletService.SendExternal(Transaction sendingTransaction, LightMoney amount, LightMoney walletBalance, Single maxFeePercent, CancellationToken cancellationToken) in /build/BTCPayServer.Plugins.LNbank/Services/Wallets/WalletService.cs:line 243
2023-11-06T07:42:12.992731792Z    at BTCPayServer.Plugins.LNbank.Services.Wallets.WalletService.SendExternal(Transaction sendingTransaction, LightMoney amount, LightMoney walletBalance, Single maxFeePercent, CancellationToken cancellationToken) in /build/BTCPayServer.Plugins.LNbank/Services/Wallets/WalletService.cs:line 275
2023-11-06T07:42:12.992735837Z    at BTCPayServer.Plugins.LNbank.Services.Wallets.WalletService.Send(Wallet wallet, BOLT11PaymentRequest bolt11, String description, LightMoney explicitAmount, String withdrawConfigId, Single maxFeePercent, CancellationToken cancellationToken) in /build/BTCPayServer.Plugins.LNbank/Services/Wallets/WalletService.cs:line 140
2023-11-06T07:42:12.992739149Z    at BTCPayServer.Plugins.LNbank.Pages.Wallets.SendModel.OnPostConfirmAsync(String walletId) in /build/BTCPayServer.Plugins.LNbank/Pages/Wallets/Send.cshtml.cs:line 171
2023-11-06T07:42:16.116774156Z info: BTCPayServer.Plugins.LNbank.Services.Wallets.WalletService: Settled transaction 72527b66-6816-481b-918a-9893dcbf66f0 (previous state: pending)
2023-11-06T07:42:16.118903388Z info: BTCPayServer.Plugins.LNbank.Services.Wallets.WalletService: Settled transaction d0c17fbd-9365-428e-a9b8-bf8d64d157a5 (previous state: pending)
2023-11-06T07:42:16.118939749Z info: BTCPayServer.Plugins.LNbank.Services.Wallets.WalletService: Settled transaction 731827d3-d07c-40f3-9095-d3d839ee19f7 (previous state: pending)
```

**Comment by dennisreimann** [comment]
What LNbank version are you running? In the transaction details, can you check what the payment request/BOLT11 looks like? 

If you need to clean this up urgently, you as an admin can delete the two extra transactions, so that the user has the correct balance.

**Comment by damanic** [comment]
BOLT11 Decoded -> https://lightningdecoder.com/lnbc10m1pj53x9tpp5455ke50ph8mkjscu20klpfh0mkgz8gw2mvcd6uda0wqufsmpz2lqdqhfdexz6m9dcsygetsdaekjaqcqzysxqrrsssp5h4vutpjyj2jad2558nmmques0agmwmd6wfhexqhcg4tyc0rl6aqs9qyyssqlnnuvs40s2jfyxs7tvs8k3nxpd0ra5dtf9fevjjpslwuht0pvn0kwchg0dlp9uu67k22nutznttkq6xasttluxlfmc0864fl63tqxdsq73hzph

I have been keeping up with BTCPS version updates, but must admit I have not looked at the plugin updates for a while.

LNbank v1.6.2!  Upgrading now.

I will manually delete the duplicate transaction entries, and point back to this issue if we encounter anything similar going forward.

**Comment by damanic** [comment]
Attempted to delete the duplicate transaction entries shown in initial screenshot and I got msg `Transaction removed.` .  But the transaction is still listed even after CTRL+F5

**Comment by dennisreimann** [comment]
Yes, you as an admin are still able to see it, because they are just "soft deleted" — I'll fix the label in that case, but the user shouldn't see them anymore and they also shouldn't be accounted for anymore.

**Comment by dennisreimann** [comment]
Fixed in LNbank v1.8.3

**Comment by damanic** [comment]
@dennisreimann 
The deleted transactions are now showing as deleted, and balance updated.  Unfortunately when the deletes appeared to fail I my retries ended up deleting the duplicates and the transaction entry that should remain.

How to rollback a soft deleted transaction entry?

![image](https://github.com/dennisreimann/btcpayserver-plugin-lnbank/assets/5227303/0eb6bdf2-059d-494a-b509-805c35de4922)

**Comment by dennisreimann** [comment]
> How to rollback a soft deleted transaction entry?

Added in LNbank v1.8.4 — access the restore functionality via the transaction details page (linked with the date).

**Comment by damanic** [comment]
Excellent work Thanks for the swift updates!
