### ISSUE TITLE
btcpay crashing while loading lnbank

### ISSUE THREAD

**Issue by Dark345** [dennisreimann/btcpayserver-plugin-lnbank#58]
Hello

BTCPay [v1.12.0-rc3](https://github.com/btcpayserver/btcpayserver/releases/tag/v1.12.0-rc3)

LNBANK [v1.8.9](https://github.com/dennisreimann/btcpayserver-plugin-lnbank/releases/tag/v1.8.9)

.NET version

```
myuser@maz-btcpay01:~/btcpayserver$ dpkg -l | grep dotnet
ii  dotnet-apphost-pack-8.0         8.0.0-1                        amd64        Microsoft.NETCore.App.Host 8.0.0
ii  dotnet-host                     8.0.0-1                        amd64        Microsoft .NET Host - 8.0.0
ii  dotnet-hostfxr-8.0              8.0.0-1                        amd64        Microsoft .NET Host FX Resolver - 8.0.0
ii  dotnet-runtime-8.0              8.0.0-1                        amd64        Microsoft.NETCore.App.Runtime 8.0.0
ii  dotnet-runtime-deps-8.0         8.0.0-1                        amd64        dotnet-runtime-deps-debian 8.0.0
ii  dotnet-sdk-8.0                  8.0.100-1                      amd64        Microsoft .NET SDK 8.0.100
ii  dotnet-targeting-pack-8.0       8.0.0-1                        amd64        Microsoft.NETCore.App.Ref 8.0.0

```

crashing on startup

```
Dec 13 21:35:02 myserver run.sh[22034]: fail: Configuration:  Disabling plugin BTCPayServer.Plugins.LNbank as it crashed on startup
Dec 13 21:35:02 myserver run.sh[22034]: System.TypeLoadException: Could not load type 'BTCPayServer.Lightning.LightningConnectionString' from assembly 'BTCPayServer.Lightning.All, Version=1.5.2.0, Culture=neutral, PublicKeyToken=null'.
Dec 13 21:35:02 myserver run.sh[22034]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
Dec 13 21:35:02 myserver run.sh[22034]:    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
Dec 13 21:35:02 myserver run.sh[22034]:    at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
Dec 13 21:35:02 myserver run.sh[22034]:    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
Dec 13 21:35:02 myserver run.sh[22034]:    at Microsoft.AspNetCore.Hosting.WebHostExtensions.StartWithTasksAsync(IWebHost webHost, CancellationToken cancellationToken) in /home/myuser/btcpayserver/BTCPayServer/Extensions/WebHostExtensions.cs:line 23
Dec 13 21:35:02 myserver run.sh[22034]:    at BTCPayServer.Program.Main(String[] args) in /home/myuser/btcpayserver/BTCPayServer/Program.cs:line 76
Dec 13 21:35:02 myserver systemd[1]: btcpay.service: Deactivated successfully.
Dec 13 21:35:02 myserver systemd[1]: btcpay.service: Consumed 4.203s CPU time.


```

**Comment by dennisreimann** [comment]
I haven't released a LNbank version compatible with the upcoming v1.12 of BTCPay Server yet. How did you end up running the RC for v1.12? I'm asking because we discourage running BTCPay Server straight from the `master` branch and would avise to upgrade only to released versions and associated tags. 

This discussion contains more details and also how to fix it, in case you are using the manual deployment.
https://github.com/btcpayserver/btcpayserver/discussions/5497

We will soon release v1.12 of BTCPay Server and I'll make sure to also publish a compatible LNbank version then.

**Comment by Dark345** [comment]
> I haven't released a LNbank version compatible with the upcoming v1.12 of BTCPay Server yet. How did you end up running the RC for v1.12? I'm asking because we discourage running BTCPay Server straight from the `master` branch and would avise to upgrade only to released versions and associated tags.
> 
> This discussion contains more details and also how to fix it, in case you are using the manual deployment. [btcpayserver/btcpayserver#5497](https://github.com/btcpayserver/btcpayserver/discussions/5497)
> 
> We will soon release v1.12 of BTCPay Server and I'll make sure to also publish a compatible LNbank version then.

Hello thanks for answering

I checked out specifically at the RC release because, new version of [NBXplorer](https://github.com/dgarage/NBXplorer) is using .NET 8, and I don't know how to manage multiple versions of .NET on same OS. Consequently, I had to use v1.12 releases because they are compilable using .NET 8.

I'm using a custom deploy of [Extended Manual Setup](https://docs.btcpayserver.org/Deployment/ManualDeploymentExtended/) of the whole thing

**Comment by dennisreimann** [comment]
Ok, I've added LNbank v1.8.9.1 as a pre-release and you will find it in the Manage Plugins section after enabling the "Show plugins in pre-release" option in Server Settings > Policies.

![grafik](https://github.com/dennisreimann/btcpayserver-plugin-lnbank/assets/886/09c4f14e-d845-4383-bfe9-0a349e011f7d)
